sudo: false # use Travis's container-based infrastructure
language: python

python: "3.6"

matrix:
  include:
    - python: "2.7"
      env:
        - TOXENV=py27-without_coverage
    - python: "2.7"
      env:
        - TOXENV=py27-with_coverage
    - python: "3.4"
      env:
        - TOXENV=py34-without_coverage
    - python: "3.4"
      env:
        - TOXENV=py34-with_coverage
    - python: "3.5"
      env:
        - TOXENV=py35-without_coverage
    - python: "3.5"
      env:
        - TOXENV=py35-with_coverage
    - python: "3.6"
      env:
        - TOXENV=py36-without_coverage
    - python: "3.6"
      env:
        - TOXENV=py36-with_coverage
    - python: "3.7"
      env:
        - TOXENV=py37-without_coverage
      # temporary workaround, see https://github.com/travis-ci/travis-ci/issues/9815
      dist: xenial
      sudo: yes
    - python: "3.7"
      env:
        - TOXENV=py37-with_coverage
      # temporary workaround, see https://github.com/travis-ci/travis-ci/issues/9815
      dist: xenial
      sudo: yes

install:
  - pip install coveralls
  - pip install virtualenv
  - pip install "tox<3"

script:
  - tox -vv

after_success:
  case "$TOXENV" in
    *with_coverage*)
      coveralls
      ;;
  esac
